apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-yandex
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane/provider-yandex
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A yandex that can be used to create Crossplane providers.
spec:
  controller:
    image: docker.io/antonglinisty/provider-yandexcloud:latest
